name: Build EXE

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Also trigger on pull requests to main

jobs:
  build-exe:
    runs-on: windows-latest  # We need a Windows environment to create an .exe

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    # Install requirements.txt
    - name: Install Requirements
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Build the .exe file
    - name: Build EXE
      run: |
        pyinstaller --onefile app.py

    # Upload the .exe file as an artifact (optional)
    - name: Upload EXE
      uses: actions/upload-artifact@v4
      with:
        name: app-exe
        path: dist/app.exe  # Path to your generated EXE file
